### ISSUE TITLE
Suggestion: add faces for diff mode

### ISSUE THREAD

**Issue by brabalan** [jabranham/mixed-pitch#3]
I have added the following faces to have diffs displayed nicely in email messages. Maybe you could add them as default as well:
- diff-added
- diff-context
- diff-file-header
- diff-function
- diff-header
- diff-hunk-header
- diff-removed
- whitespace-space

**Comment by jabranham** [comment]
Thanks! I added the diff faces. I left whitespace-space out since it
would look quite weird to have fixed-pitch whitespace with
variable-pitch font otherwise, if people wanted to use whitespace-mode
in e.g. test-mode.

**Comment by brabalan** [comment]
Thank you. I understand regarding whitespace, although it's unfortunate diff uses it to display its white spaces.
